[tool.poetry]
name = "pepsflow"
version = "0.1.0"
description = ""
authors = ["DerkNiessink <derk@niessink.com>"]
readme = "README.md"
packages =[{include = "pepsflow", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.3.3"
tqdm = "^4.66.5"
matplotlib = "^3.9.2"
scienceplots = "^2.1.1"

[tool.poetry.scripts]
pepsflow = "pepsflow.run:main"
plot = "pepsflow.plot:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
