[tool.poetry]
name = "pepsflow"
version = "0.1.0"
description = ""
authors = ["DerkNiessink <derk@niessink.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
asttokens = "2.4.1"
build = "1.2.2"
CacheControl = "0.14.0"
certifi = "2024.8.30"
charset-normalizer = "3.3.2"
cleo = "2.1.0"
colorama = "0.4.6"
comm = "0.2.2"
contourpy = "1.3.0"
crashtest = "0.4.1"
cycler = "0.12.1"
debugpy = "1.8.5"
decorator = "5.1.1"
distlib = "0.3.8"
dulwich = "0.21.7"
executing = "2.1.0"
fastjsonschema = "2.20.0"
filelock = "3.16.0"
fonttools = "4.53.1"
fsspec = "2024.9.0"
gprof2dot = "2024.6.6"
idna = "3.10"
installer = "0.7.0"
ipykernel = "6.29.5"
ipython = "8.27.0"
jedi = "0.19.1"
Jinja2 = "3.1.4"
jupyter_client = "8.6.2"
jupyter_core = "5.7.2"
keyring = "24.3.1"
kiwisolver = "1.4.7"
MarkupSafe = "2.1.5"
matplotlib = "3.9.2"
matplotlib-inline = "0.1.7"
more-itertools = "10.5.0"
mpmath = "1.3.0"
msgpack = "1.1.0"
ncon = "2.0.0"
nest-asyncio = "1.6.0"
networkx = "3.3"
numpy = "2.1.1"
packaging = "24.1"
parso = "0.8.4"
pexpect = "4.9.0"
pillow = "10.4.0"
pkginfo = "1.11.1"
platformdirs = "4.3.2"
poetry = "1.8.3"
poetry-core = "1.9.0"
poetry-plugin-export = "1.8.0"
prompt_toolkit = "3.0.47"
psutil = "6.0.0"
ptyprocess = "0.7.0"
pure_eval = "0.2.3"
Pygments = "2.18.0"
pyparsing = "3.1.4"
pyproject_hooks = "1.1.0"
python-dateutil = "2.9.0.post0"
pywin32 = "306"
pywin32-ctypes = "0.2.3"
pyzmq = "26.2.0"
rapidfuzz = "3.9.7"
requests = "2.32.3"
requests-toolbelt = "1.0.0"
SciencePlots = "2.1.1"
scipy = "1.14.1"
setuptools = "74.1.2"
shellingham = "1.5.4"
six = "1.16.0"
stack-data = "0.6.3"
sympy = "1.13.2"
tomlkit = "0.13.2"
torch = "2.4.1+cu124"
torchaudio = "2.4.1+cu124"
torchvision = "0.19.1+cu124"
tornado = "6.4.1"
tqdm = "4.66.5"
traitlets = "5.14.3"
trove-classifiers = "2024.9.12"
typing_extensions = "4.12.2"
urllib3 = "2.2.3"
virtualenv = "20.26.5"
wcwidth = "0.2.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
